/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.leave.model.impl;

import com.adjecti.leave.model.LeaveReason;
import com.adjecti.leave.model.LeaveReasonModel;
import com.adjecti.leave.model.LeaveReasonSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LeaveReason service. Represents a row in the &quot;Leave_LeaveReason&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LeaveReasonModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveReasonImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveReasonImpl
 * @generated
 */
@JSON(strict = true)
public class LeaveReasonModelImpl
	extends BaseModelImpl<LeaveReason> implements LeaveReasonModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave reason model instance should use the <code>LeaveReason</code> interface instead.
	 */
	public static final String TABLE_NAME = "Leave_LeaveReason";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"leaveReasonId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"leaveReasonCode", Types.VARCHAR},
		{"leaveReasonDescription", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("leaveReasonId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("leaveReasonCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("leaveReasonDescription", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Leave_LeaveReason (uuid_ VARCHAR(75) null,leaveReasonId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,leaveReasonCode VARCHAR(75) null,leaveReasonDescription VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Leave_LeaveReason";

	public static final String ORDER_BY_JPQL =
		" ORDER BY leaveReason.leaveReasonDescription ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Leave_LeaveReason.leaveReasonDescription ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVEREASONDESCRIPTION_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static LeaveReason toModel(LeaveReasonSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LeaveReason model = new LeaveReasonImpl();

		model.setUuid(soapModel.getUuid());
		model.setLeaveReasonId(soapModel.getLeaveReasonId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setLeaveReasonCode(soapModel.getLeaveReasonCode());
		model.setLeaveReasonDescription(soapModel.getLeaveReasonDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<LeaveReason> toModels(LeaveReasonSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LeaveReason> models = new ArrayList<LeaveReason>(
			soapModels.length);

		for (LeaveReasonSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public LeaveReasonModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveReasonId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveReasonId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveReasonId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveReason.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveReason.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LeaveReason, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LeaveReason, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveReason, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LeaveReason)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LeaveReason, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LeaveReason, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LeaveReason)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LeaveReason, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LeaveReason, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LeaveReason>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LeaveReason.class.getClassLoader(), LeaveReason.class,
			ModelWrapper.class);

		try {
			Constructor<LeaveReason> constructor =
				(Constructor<LeaveReason>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<LeaveReason, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LeaveReason, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LeaveReason, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LeaveReason, Object>>();
		Map<String, BiConsumer<LeaveReason, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LeaveReason, ?>>();

		attributeGetterFunctions.put("uuid", LeaveReason::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<LeaveReason, String>)LeaveReason::setUuid);
		attributeGetterFunctions.put(
			"leaveReasonId", LeaveReason::getLeaveReasonId);
		attributeSetterBiConsumers.put(
			"leaveReasonId",
			(BiConsumer<LeaveReason, Long>)LeaveReason::setLeaveReasonId);
		attributeGetterFunctions.put("groupId", LeaveReason::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<LeaveReason, Long>)LeaveReason::setGroupId);
		attributeGetterFunctions.put("companyId", LeaveReason::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<LeaveReason, Long>)LeaveReason::setCompanyId);
		attributeGetterFunctions.put("userId", LeaveReason::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<LeaveReason, Long>)LeaveReason::setUserId);
		attributeGetterFunctions.put("userName", LeaveReason::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<LeaveReason, String>)LeaveReason::setUserName);
		attributeGetterFunctions.put("createDate", LeaveReason::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<LeaveReason, Date>)LeaveReason::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", LeaveReason::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<LeaveReason, Date>)LeaveReason::setModifiedDate);
		attributeGetterFunctions.put(
			"leaveReasonCode", LeaveReason::getLeaveReasonCode);
		attributeSetterBiConsumers.put(
			"leaveReasonCode",
			(BiConsumer<LeaveReason, String>)LeaveReason::setLeaveReasonCode);
		attributeGetterFunctions.put(
			"leaveReasonDescription", LeaveReason::getLeaveReasonDescription);
		attributeSetterBiConsumers.put(
			"leaveReasonDescription",
			(BiConsumer<LeaveReason, String>)
				LeaveReason::setLeaveReasonDescription);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getLeaveReasonId() {
		return _leaveReasonId;
	}

	@Override
	public void setLeaveReasonId(long leaveReasonId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveReasonId = leaveReasonId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getLeaveReasonCode() {
		if (_leaveReasonCode == null) {
			return "";
		}
		else {
			return _leaveReasonCode;
		}
	}

	@Override
	public void setLeaveReasonCode(String leaveReasonCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveReasonCode = leaveReasonCode;
	}

	@JSON
	@Override
	public String getLeaveReasonDescription() {
		if (_leaveReasonDescription == null) {
			return "";
		}
		else {
			return _leaveReasonDescription;
		}
	}

	@Override
	public void setLeaveReasonDescription(String leaveReasonDescription) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveReasonDescription = leaveReasonDescription;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLeaveReasonDescription() {
		return getColumnOriginalValue("leaveReasonDescription");
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LeaveReason.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LeaveReason.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LeaveReason toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LeaveReason>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveReasonImpl leaveReasonImpl = new LeaveReasonImpl();

		leaveReasonImpl.setUuid(getUuid());
		leaveReasonImpl.setLeaveReasonId(getLeaveReasonId());
		leaveReasonImpl.setGroupId(getGroupId());
		leaveReasonImpl.setCompanyId(getCompanyId());
		leaveReasonImpl.setUserId(getUserId());
		leaveReasonImpl.setUserName(getUserName());
		leaveReasonImpl.setCreateDate(getCreateDate());
		leaveReasonImpl.setModifiedDate(getModifiedDate());
		leaveReasonImpl.setLeaveReasonCode(getLeaveReasonCode());
		leaveReasonImpl.setLeaveReasonDescription(getLeaveReasonDescription());

		leaveReasonImpl.resetOriginalValues();

		return leaveReasonImpl;
	}

	@Override
	public int compareTo(LeaveReason leaveReason) {
		int value = 0;

		value = getLeaveReasonDescription().compareTo(
			leaveReason.getLeaveReasonDescription());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LeaveReason)) {
			return false;
		}

		LeaveReason leaveReason = (LeaveReason)object;

		long primaryKey = leaveReason.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveReason> toCacheModel() {
		LeaveReasonCacheModel leaveReasonCacheModel =
			new LeaveReasonCacheModel();

		leaveReasonCacheModel.uuid = getUuid();

		String uuid = leaveReasonCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			leaveReasonCacheModel.uuid = null;
		}

		leaveReasonCacheModel.leaveReasonId = getLeaveReasonId();

		leaveReasonCacheModel.groupId = getGroupId();

		leaveReasonCacheModel.companyId = getCompanyId();

		leaveReasonCacheModel.userId = getUserId();

		leaveReasonCacheModel.userName = getUserName();

		String userName = leaveReasonCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			leaveReasonCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveReasonCacheModel.createDate = createDate.getTime();
		}
		else {
			leaveReasonCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveReasonCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leaveReasonCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leaveReasonCacheModel.leaveReasonCode = getLeaveReasonCode();

		String leaveReasonCode = leaveReasonCacheModel.leaveReasonCode;

		if ((leaveReasonCode != null) && (leaveReasonCode.length() == 0)) {
			leaveReasonCacheModel.leaveReasonCode = null;
		}

		leaveReasonCacheModel.leaveReasonDescription =
			getLeaveReasonDescription();

		String leaveReasonDescription =
			leaveReasonCacheModel.leaveReasonDescription;

		if ((leaveReasonDescription != null) &&
			(leaveReasonDescription.length() == 0)) {

			leaveReasonCacheModel.leaveReasonDescription = null;
		}

		return leaveReasonCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LeaveReason, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LeaveReason, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveReason, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LeaveReason)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LeaveReason, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LeaveReason, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveReason, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LeaveReason)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LeaveReason>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _leaveReasonId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _leaveReasonCode;
	private String _leaveReasonDescription;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LeaveReason, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LeaveReason)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("leaveReasonId", _leaveReasonId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("leaveReasonCode", _leaveReasonCode);
		_columnOriginalValues.put(
			"leaveReasonDescription", _leaveReasonDescription);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("leaveReasonId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("leaveReasonCode", 256L);

		columnBitmasks.put("leaveReasonDescription", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LeaveReason _escapedModel;

}