/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.leave.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LeaveApplication service. Represents a row in the &quot;Leave_LeaveApplication&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.leave.model.impl.LeaveApplicationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.leave.model.impl.LeaveApplicationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveApplication
 * @generated
 */
@ProviderType
public interface LeaveApplicationModel
	extends BaseModel<LeaveApplication>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave application model instance should use the {@link LeaveApplication} interface instead.
	 */

	/**
	 * Returns the primary key of this leave application.
	 *
	 * @return the primary key of this leave application
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leave application.
	 *
	 * @param primaryKey the primary key of this leave application
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this leave application.
	 *
	 * @return the uuid of this leave application
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this leave application.
	 *
	 * @param uuid the uuid of this leave application
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the leave application ID of this leave application.
	 *
	 * @return the leave application ID of this leave application
	 */
	public long getLeaveApplicationId();

	/**
	 * Sets the leave application ID of this leave application.
	 *
	 * @param leaveApplicationId the leave application ID of this leave application
	 */
	public void setLeaveApplicationId(long leaveApplicationId);

	/**
	 * Returns the group ID of this leave application.
	 *
	 * @return the group ID of this leave application
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this leave application.
	 *
	 * @param groupId the group ID of this leave application
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this leave application.
	 *
	 * @return the company ID of this leave application
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this leave application.
	 *
	 * @param companyId the company ID of this leave application
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this leave application.
	 *
	 * @return the user ID of this leave application
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this leave application.
	 *
	 * @param userId the user ID of this leave application
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this leave application.
	 *
	 * @return the user uuid of this leave application
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this leave application.
	 *
	 * @param userUuid the user uuid of this leave application
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this leave application.
	 *
	 * @return the user name of this leave application
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this leave application.
	 *
	 * @param userName the user name of this leave application
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this leave application.
	 *
	 * @return the create date of this leave application
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this leave application.
	 *
	 * @param createDate the create date of this leave application
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this leave application.
	 *
	 * @return the modified date of this leave application
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this leave application.
	 *
	 * @param modifiedDate the modified date of this leave application
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the leave reason ID of this leave application.
	 *
	 * @return the leave reason ID of this leave application
	 */
	public long getLeaveReasonId();

	/**
	 * Sets the leave reason ID of this leave application.
	 *
	 * @param leaveReasonId the leave reason ID of this leave application
	 */
	public void setLeaveReasonId(long leaveReasonId);

	/**
	 * Returns the employee ID of this leave application.
	 *
	 * @return the employee ID of this leave application
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this leave application.
	 *
	 * @param employeeId the employee ID of this leave application
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the leave type ID of this leave application.
	 *
	 * @return the leave type ID of this leave application
	 */
	public long getLeaveTypeId();

	/**
	 * Sets the leave type ID of this leave application.
	 *
	 * @param leaveTypeId the leave type ID of this leave application
	 */
	public void setLeaveTypeId(long leaveTypeId);

	/**
	 * Returns the start date of this leave application.
	 *
	 * @return the start date of this leave application
	 */
	@AutoEscape
	public String getStartDate();

	/**
	 * Sets the start date of this leave application.
	 *
	 * @param startDate the start date of this leave application
	 */
	public void setStartDate(String startDate);

	/**
	 * Returns the end date of this leave application.
	 *
	 * @return the end date of this leave application
	 */
	@AutoEscape
	public String getEndDate();

	/**
	 * Sets the end date of this leave application.
	 *
	 * @param endDate the end date of this leave application
	 */
	public void setEndDate(String endDate);

	/**
	 * Returns the start in half day of this leave application.
	 *
	 * @return the start in half day of this leave application
	 */
	public boolean getStartInHalfDay();

	/**
	 * Returns <code>true</code> if this leave application is start in half day.
	 *
	 * @return <code>true</code> if this leave application is start in half day; <code>false</code> otherwise
	 */
	public boolean isStartInHalfDay();

	/**
	 * Sets whether this leave application is start in half day.
	 *
	 * @param startInHalfDay the start in half day of this leave application
	 */
	public void setStartInHalfDay(boolean startInHalfDay);

	/**
	 * Returns the end in half day of this leave application.
	 *
	 * @return the end in half day of this leave application
	 */
	public boolean getEndInHalfDay();

	/**
	 * Returns <code>true</code> if this leave application is end in half day.
	 *
	 * @return <code>true</code> if this leave application is end in half day; <code>false</code> otherwise
	 */
	public boolean isEndInHalfDay();

	/**
	 * Sets whether this leave application is end in half day.
	 *
	 * @param endInHalfDay the end in half day of this leave application
	 */
	public void setEndInHalfDay(boolean endInHalfDay);

	/**
	 * Returns the actual joining date of this leave application.
	 *
	 * @return the actual joining date of this leave application
	 */
	@AutoEscape
	public String getActualJoiningDate();

	/**
	 * Sets the actual joining date of this leave application.
	 *
	 * @param actualJoiningDate the actual joining date of this leave application
	 */
	public void setActualJoiningDate(String actualJoiningDate);

	/**
	 * Returns the remark of this leave application.
	 *
	 * @return the remark of this leave application
	 */
	@AutoEscape
	public String getRemark();

	/**
	 * Sets the remark of this leave application.
	 *
	 * @param remark the remark of this leave application
	 */
	public void setRemark(String remark);

	/**
	 * Returns the document ID of this leave application.
	 *
	 * @return the document ID of this leave application
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this leave application.
	 *
	 * @param documentId the document ID of this leave application
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the status of this leave application.
	 *
	 * @return the status of this leave application
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this leave application.
	 *
	 * @param status the status of this leave application
	 */
	public void setStatus(String status);

	/**
	 * Returns the reporting manager of this leave application.
	 *
	 * @return the reporting manager of this leave application
	 */
	@AutoEscape
	public String getReportingManager();

	/**
	 * Sets the reporting manager of this leave application.
	 *
	 * @param reportingManager the reporting manager of this leave application
	 */
	public void setReportingManager(String reportingManager);

	/**
	 * Returns the join in half day of this leave application.
	 *
	 * @return the join in half day of this leave application
	 */
	@AutoEscape
	public String getJoinInHalfDay();

	/**
	 * Sets the join in half day of this leave application.
	 *
	 * @param joinInHalfDay the join in half day of this leave application
	 */
	public void setJoinInHalfDay(String joinInHalfDay);

}