/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.leave.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LeaveReason service. Represents a row in the &quot;Leave_LeaveReason&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.leave.model.impl.LeaveReasonModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.leave.model.impl.LeaveReasonImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveReason
 * @generated
 */
@ProviderType
public interface LeaveReasonModel
	extends BaseModel<LeaveReason>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave reason model instance should use the {@link LeaveReason} interface instead.
	 */

	/**
	 * Returns the primary key of this leave reason.
	 *
	 * @return the primary key of this leave reason
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leave reason.
	 *
	 * @param primaryKey the primary key of this leave reason
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this leave reason.
	 *
	 * @return the uuid of this leave reason
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this leave reason.
	 *
	 * @param uuid the uuid of this leave reason
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the leave reason ID of this leave reason.
	 *
	 * @return the leave reason ID of this leave reason
	 */
	public long getLeaveReasonId();

	/**
	 * Sets the leave reason ID of this leave reason.
	 *
	 * @param leaveReasonId the leave reason ID of this leave reason
	 */
	public void setLeaveReasonId(long leaveReasonId);

	/**
	 * Returns the group ID of this leave reason.
	 *
	 * @return the group ID of this leave reason
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this leave reason.
	 *
	 * @param groupId the group ID of this leave reason
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this leave reason.
	 *
	 * @return the company ID of this leave reason
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this leave reason.
	 *
	 * @param companyId the company ID of this leave reason
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this leave reason.
	 *
	 * @return the user ID of this leave reason
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this leave reason.
	 *
	 * @param userId the user ID of this leave reason
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this leave reason.
	 *
	 * @return the user uuid of this leave reason
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this leave reason.
	 *
	 * @param userUuid the user uuid of this leave reason
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this leave reason.
	 *
	 * @return the user name of this leave reason
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this leave reason.
	 *
	 * @param userName the user name of this leave reason
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this leave reason.
	 *
	 * @return the create date of this leave reason
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this leave reason.
	 *
	 * @param createDate the create date of this leave reason
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this leave reason.
	 *
	 * @return the modified date of this leave reason
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this leave reason.
	 *
	 * @param modifiedDate the modified date of this leave reason
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the leave reason code of this leave reason.
	 *
	 * @return the leave reason code of this leave reason
	 */
	@AutoEscape
	public String getLeaveReasonCode();

	/**
	 * Sets the leave reason code of this leave reason.
	 *
	 * @param leaveReasonCode the leave reason code of this leave reason
	 */
	public void setLeaveReasonCode(String leaveReasonCode);

	/**
	 * Returns the leave reason description of this leave reason.
	 *
	 * @return the leave reason description of this leave reason
	 */
	@AutoEscape
	public String getLeaveReasonDescription();

	/**
	 * Sets the leave reason description of this leave reason.
	 *
	 * @param leaveReasonDescription the leave reason description of this leave reason
	 */
	public void setLeaveReasonDescription(String leaveReasonDescription);

}